package:
  name: cc-notebook
  version: 0.1

source:
  git_url: https://github.com/Clyde-fare/cc_notebook.git
build:
  number: 1

  entry_points:
    - cc_notebook_init = cc_notebook.install:cc_notebook_init

requirements:
  build:
    - python
    - setuptools

  run:
    - numpy
    - ase ==3.8.2.dev
    - ase-extensions ==0.1
    - molmod ==1.01
    - ipython-notebook >=2
  
about:
  summary: This is the cc-notebook recipe
